/**
 * Seed do CRM Notes — dados de exemplo realistas de uma empresa de tecnologia.
 * Os horários são relativos ao momento do primeiro start do servidor para que
 * os alarmes possam ser testados imediatamente.
 */

const MIN = 60 * 1000
const HOUR = 60 * MIN
const DAY = 24 * HOUR

const now = () => Date.now()
const iso = (ts) => new Date(ts).toISOString()
const at = (ms) => iso(now() + ms)
const ago = (ms) => iso(now() - ms)

/** Data/hora local (America/Sao_Paulo não é aplicado; usa o fuso do servidor). */
function localDateTime(msFromNow, hour = 9, minute = 0) {
  const d = new Date(now() + msFromNow)
  d.setHours(hour, minute, 0, 0)
  return d.toISOString()
}

export function buildSeed() {
  const categories = [
    { id: 'cat_comercial', name: 'Comercial', color: 'azul', createdAt: ago(30 * DAY) },
    { id: 'cat_financeiro', name: 'Financeiro', color: 'esmeralda', createdAt: ago(30 * DAY) },
    { id: 'cat_suporte', name: 'Suporte', color: 'laranja', createdAt: ago(28 * DAY) },
    { id: 'cat_dev', name: 'Desenvolvimento', color: 'violeta', createdAt: ago(28 * DAY) },
    { id: 'cat_reunioes', name: 'Reuniões', color: 'ciano', createdAt: ago(25 * DAY) },
    { id: 'cat_marketing', name: 'Marketing', color: 'rosa', createdAt: ago(20 * DAY) },
    { id: 'cat_infra', name: 'Infraestrutura', color: 'grafite', createdAt: ago(18 * DAY) },
    { id: 'cat_produto', name: 'Produto', color: 'indigo', createdAt: ago(15 * DAY) },
  ]

  let seq = 0
  const n = (data) => ({
    id: `note_${String(++seq).padStart(3, '0')}`,
    title: '',
    content: '',
    color: 'padrao',
    categoryId: null,
    tags: [],
    pinned: false,
    archived: false,
    trashed: false,
    trashedAt: null,
    priority: 'media',
    stage: 'prospeccao',
    inPipeline: false,
    order: seq,
    client: '',
    company: '',
    email: '',
    phone: '',
    dealValue: 0,
    dueDate: null,
    checklist: [],
    history: [],
    createdAt: ago(20 * DAY),
    updatedAt: ago(2 * DAY),
    ...data,
  })

  const check = (text, done = false) => ({ id: `chk_${Math.random().toString(36).slice(2, 9)}`, text, done })
  const hist = (text, when) => ({ id: `hst_${Math.random().toString(36).slice(2, 9)}`, at: when, text })

  const notes = [
    // ───────────── PIPELINE · PROSPECÇÃO ─────────────
    n({
      id: 'note_lead_andrade',
      title: 'Grupo Andrade — plataforma de gestão de obras',
      content:
        'Lead indicado pelo Ricardo (LinkedIn). Grupo com 4 filiais e 180 colaboradores.\n\nDor principal: controle de obras em planilhas, sem visão consolidada de custos.\nOrçamento estimado: R$ 85k para implantação + R$ 6,5k/mês de manutenção.\n\nPróximo passo: agendar diagnóstico técnico com o TI deles.',
      color: 'azul',
      categoryId: 'cat_comercial',
      tags: ['lead', 'linkedin', 'obras'],
      pinned: true,
      priority: 'alta',
      stage: 'prospeccao',
      inPipeline: true,
      order: 1,
      company: 'Grupo Andrade Engenharia',
      client: 'Ricardo Menezes',
      email: 'ricardo.menezes@grupoandrade.com.br',
      phone: '(11) 98812-4477',
      dealValue: 85000,
      dueDate: at(4 * DAY),
      checklist: [check('Confirmar orçamento com o diretor', true), check('Enviar e-mail de apresentação'), check('Ligar para o TI (Marcos)')],
      history: [
        hist('Lead criado a partir de indicação no LinkedIn.', ago(6 * DAY)),
        hist('Ricardo confirmou interesse e pediu material institucional.', ago(3 * DAY)),
      ],
      createdAt: ago(6 * DAY),
      updatedAt: ago(1 * DAY),
    }),
    n({
      id: 'note_lead_sabor',
      title: 'Sabor & Cia — app de delivery próprio',
      content:
        'Rede de 12 restaurantes. Quer sair dos apps de terceiros (taxa de 27%).\n\nEscopo inicial: app do cliente + painel do lojista + integração com iFood.\nConcorrentes cotados: 2 agências locais.\n\nPonto de atenção: prazo curto — querem lançar antes do verão.',
      color: 'ceu',
      categoryId: 'cat_comercial',
      tags: ['lead', 'delivery', 'app'],
      priority: 'media',
      stage: 'prospeccao',
      inPipeline: true,
      order: 2,
      company: 'Sabor & Cia Alimentos',
      client: 'Fernanda Lopes',
      email: 'fernanda@saborecia.com.br',
      phone: '(21) 99745-1120',
      dealValue: 62000,
      createdAt: ago(9 * DAY),
      updatedAt: ago(4 * DAY),
    }),
    n({
      id: 'note_lead_vega',
      title: 'Metalúrgica Vega — migração de ERP legado',
      content:
        'ERP atual (Delphi, 2009) sem suporte do fornecedor. Buscam migração para nuvem.\n\nComplexidade alta: 14 anos de dados fiscais, integração com o sistema da contabilidade.\nIndicado trabalhar em fases: cadastros → financeiro → fiscal.\n\nAguardando a relação de processos que a Vega vai enviar.',
      color: 'cinza',
      categoryId: 'cat_comercial',
      tags: ['lead', 'erp', 'migracao'],
      priority: 'media',
      stage: 'prospeccao',
      inPipeline: true,
      order: 3,
      company: 'Metalúrgica Vega LTDA',
      client: 'Joel Barros (Diretor Industrial)',
      email: 'joel.barros@vega-metal.com.br',
      phone: '(19) 98123-0099',
      dealValue: 140000,
      createdAt: ago(14 * DAY),
      updatedAt: ago(5 * DAY),
    }),
    n({
      id: 'note_lead_bemviver',
      title: 'Clínica Bem Viver — site + campanha de captação',
      content:
        'Projeto menor, boa porta de entrada. Landing page + Google Ads + agendamento online.\n\nVerba de mídia: R$ 4k/mês (gerenciada por eles).\nProjeto: R$ 18k.\n\nEnviar portfólio de saúde.',
      color: 'esmeralda',
      categoryId: 'cat_comercial',
      tags: ['lead', 'site', 'saude'],
      priority: 'baixa',
      stage: 'prospeccao',
      inPipeline: true,
      order: 4,
      company: 'Clínica Bem Viver',
      client: 'Dra. Patrícia Nunes',
      email: 'contato@clinicabemviver.com.br',
      phone: '(31) 99880-3344',
      dealValue: 18000,
      createdAt: ago(3 * DAY),
      updatedAt: ago(3 * DAY),
    }),

    // ───────────── PIPELINE · 1º ATENDIMENTO ─────────────
    n({
      id: 'note_atend_horizonte',
      title: 'Construtora Horizonte — diagnóstico técnico',
      content:
        'Call de 45 min (Zoom) com o time de operações.\n\nNecessidades mapeadas:\n• Diário de obra digital com fotos georreferenciadas\n• Medição e medição contratual automática\n• Integração com o financeiro (Conta Azul)\n\nDecisor: diretor de operações. Influenciador: gerente de planejamento.\nOrçamento previsto para janeiro.',
      color: 'indigo',
      categoryId: 'cat_comercial',
      tags: ['lead', 'call', 'diagnostico'],
      pinned: true,
      priority: 'alta',
      stage: 'atendimento',
      inPipeline: true,
      order: 1,
      company: 'Construtora Horizonte',
      client: 'Marcos Tavares',
      email: 'marcos.tavares@horizonteconst.com.br',
      phone: '(11) 97455-2210',
      dealValue: 96000,
      dueDate: at(2 * DAY),
      history: [
        hist('Call de diagnóstico realizada (45 min).', ago(2 * DAY)),
        hist('Anexado escopo preliminar em PDF para validação.', ago(1 * DAY)),
      ],
      createdAt: ago(11 * DAY),
      updatedAt: ago(1 * DAY),
    }),
    n({
      id: 'note_atend_fitlife',
      title: 'FitLife Academias — automação de atendimento no WhatsApp',
      content:
        '3 unidades, ~4.200 alunos. Atendimento manual das 8h às 20h.\n\nProposta de valor: bot de matrícula, cobrança e retenção com IA.\nVolume estimado: 900 conversas/mês.\n\nPrecisamos estimar custo de API de IA por conversa antes de precificar.',
      color: 'turquesa',
      categoryId: 'cat_comercial',
      tags: ['lead', 'whatsapp', 'ia'],
      priority: 'alta',
      stage: 'atendimento',
      inPipeline: true,
      order: 2,
      company: 'FitLife Academias',
      client: 'Bruno Salles',
      email: 'bruno@fitlife.com.br',
      phone: '(41) 99623-7788',
      dealValue: 34500,
      dueDate: at(6 * DAY),
      createdAt: ago(8 * DAY),
      updatedAt: ago(2 * DAY),
    }),
    n({
      id: 'note_atend_logplus',
      title: 'LogPlus Transportes — suporte 24/7 e SLA',
      content:
        'Operação crítica: 60 veículos rastreados, paradas não podem passar de 30 min.\n\nPedem SLA de 15 min para incidentes graves e plantão de fim de semana.\nAtendimento atual: R$ 3,2k/mês com concorrente que não cumpre SLA.\n\nProposta: R$ 5,8k/mês com plantão escalonado. Precisa de aprovação do board.',
      color: 'ambar',
      categoryId: 'cat_suporte',
      tags: ['lead', 'sla', 'suporte'],
      priority: 'urgente',
      stage: 'atendimento',
      inPipeline: true,
      order: 3,
      company: 'LogPlus Transportes',
      client: 'Simone Ribeiro',
      email: 'simone.ribeiro@logplus.com.br',
      phone: '(51) 99334-4477',
      dealValue: 69600,
      createdAt: ago(5 * DAY),
      updatedAt: ago(1 * DAY),
    }),

    // ───────────── PIPELINE · CRIAÇÃO ─────────────
    n({
      id: 'note_cria_cristal',
      title: 'Vidraçaria Cristal — sistema de orçamentos',
      content:
        'Desenvolvimento em andamento (sprint 2 de 4).\n\n✅ Cadastro de vidros e perfis\n✅ Cálculo automático por m²\n🔧 Geração de PDF do orçamento\n⬜ App do vendedor (offline)\n\nReunião de revisão de sprint toda quinta às 16h.',
      color: 'violeta',
      categoryId: 'cat_dev',
      tags: ['projeto', 'sprint', 'orcamento'],
      pinned: true,
      priority: 'alta',
      stage: 'criacao',
      inPipeline: true,
      order: 1,
      company: 'Vidraçaria Cristal',
      client: 'Alexandre Prado',
      email: 'alexandre@vidracariacristal.com.br',
      phone: '(47) 98811-5566',
      dealValue: 42000,
      dueDate: at(12 * DAY),
      checklist: [check('Cadastro de vidros e perfis', true), check('Cálculo por m²', true), check('Geração de PDF', true), check('App offline do vendedor', false)],
      history: [
        hist('Sprint 1 entregue e aprovada pelo cliente.', ago(9 * DAY)),
        hist('Ajustado cálculo de desperdício para chapas de 6m.', ago(4 * DAY)),
      ],
      createdAt: ago(24 * DAY),
      updatedAt: ago(2 * DAY),
    }),
    n({
      id: 'note_cria_norte',
      title: 'Distribuidora Norte — integração NF-e e estoque',
      content:
        'Integração SEFAZ homologada em ambiente de teste.\nEmissão de NF-e, CT-e e movimentação de estoque em 3 depósitos.\n\nPendência: certificado digital A1 do cliente vence em 18/10 — cobrar renovação.\nWebhook de atualização de estoque: 1 chamada a cada 5 min.',
      color: 'ciano',
      categoryId: 'cat_dev',
      tags: ['projeto', 'nfe', 'integracao'],
      priority: 'urgente',
      stage: 'criacao',
      inPipeline: true,
      order: 2,
      company: 'Distribuidora Norte',
      client: 'Carla Menezes',
      email: 'carla.menezes@distnorte.com.br',
      phone: '(92) 99455-1212',
      dealValue: 112000,
      dueDate: at(9 * DAY),
      history: [hist('Ambiente de homologação aprovado.', ago(3 * DAY))],
      createdAt: ago(30 * DAY),
      updatedAt: ago(1 * DAY),
    }),
    n({
      id: 'note_cria_agrosul',
      title: 'AgroSul Cooperativa — dashboard de BI',
      content:
        'Modelagem dimensional concluída (fato_safra, dim_talhao, dim_insumo).\nDashboards: produtividade por talhão, custo por hectare, previsão de safra.\n\nFonte: 6 planilhas + ERP TOTVS.\nTreinamento dos 12 gestores agendado para depois da entrega.',
      color: 'limao',
      categoryId: 'cat_produto',
      tags: ['projeto', 'bi', 'dados'],
      priority: 'media',
      stage: 'criacao',
      inPipeline: true,
      order: 3,
      company: 'AgroSul Cooperativa',
      client: 'Eng. Débora Klein',
      email: 'debora.klein@agrosul.coop.br',
      phone: '(55) 99788-2323',
      dealValue: 78000,
      dueDate: at(18 * DAY),
      createdAt: ago(20 * DAY),
      updatedAt: ago(6 * DAY),
    }),

    // ───────────── PIPELINE · APRESENTAÇÃO ─────────────
    n({
      id: 'note_apres_prisma',
      title: 'Seguradora Prisma — portal do cliente',
      content:
        'Apresentação feita para 6 pessoas (diretoria + TI). Reação positiva ao protótipo.\n\nDúvidas levantadas:\n• LGPD e retenção de dados (respondemos com o anexo de segurança)\n• Prazo de 4 meses (aceitaram 5)\n• Suporte de migração de 240 mil apólices\n\nAguardando aprovação formal do comitê na sexta.',
      color: 'roxo',
      categoryId: 'cat_comercial',
      tags: ['proposta', 'apresentacao', 'lgpd'],
      pinned: true,
      priority: 'urgente',
      stage: 'apresentacao',
      inPipeline: true,
      order: 1,
      company: 'Seguradora Prisma',
      client: 'Helena Ferraz (CDO)',
      email: 'helena.ferraz@prismaseg.com.br',
      phone: '(11) 96233-8899',
      dealValue: 185000,
      dueDate: at(3 * DAY),
      history: [
        hist('Proposta comercial enviada (R$ 185k, 5 meses).', ago(4 * DAY)),
        hist('Apresentação executada para 6 stakeholders.', ago(1 * DAY)),
      ],
      createdAt: ago(35 * DAY),
      updatedAt: ago(6 * MIN),
    }),
    n({
      id: 'note_apres_energia',
      title: 'Energia Renovável BR — app de campo offline',
      content:
        'Apresentação agendada para quinta 10h (online, 40 min).\n\nRoteiro: problema → protótipo → cronograma → investimento → próximos passos.\nDemonstração ao vivo do app offline (tablet em modo avião).\n\nPontos de risco: conexão instável em campo, sincronização de fotos pesadas.',
      color: 'amarelo',
      categoryId: 'cat_comercial',
      tags: ['apresentacao', 'app', 'offline'],
      priority: 'alta',
      stage: 'apresentacao',
      inPipeline: true,
      order: 2,
      company: 'Energia Renovável BR',
      client: 'Tiago Mourão',
      email: 'tiago.mourao@energiabr.com.br',
      phone: '(85) 99122-3344',
      dealValue: 132000,
      dueDate: at(1 * DAY),
      createdAt: ago(16 * DAY),
      updatedAt: ago(1 * DAY),
    }),
    n({
      id: 'note_apres_novaera',
      title: 'Escola Nova Era — CRM de captação de alunos',
      content:
        'Segunda apresentação (a primeira foi só para a secretaria).\nAgora com a direção, foco em ROI: taxa de conversão de matrículas atual é 12%.\n\nSimulação apresentada: 1.100 leads/ano com CRM + régua de automação → meta de 19%.\nPedem uma versão de contrato com pagamento trimestral.',
      color: 'areia',
      categoryId: 'cat_comercial',
      tags: ['apresentacao', 'educacao', 'roi'],
      priority: 'media',
      stage: 'apresentacao',
      inPipeline: true,
      order: 3,
      company: 'Escola Nova Era',
      client: 'Diretora Cláudia Ramos',
      email: 'claudia.ramos@novaera.edu.br',
      phone: '(62) 99877-6655',
      dealValue: 54000,
      dueDate: at(8 * DAY),
      createdAt: ago(13 * DAY),
      updatedAt: ago(3 * DAY),
    }),

    // ───────────── PIPELINE · VENDA ─────────────
    n({
      id: 'note_venda_bemestar',
      title: 'Rede BemEstar — plataforma de vendas fechada em contrato',
      content:
        'Contrato assinado digitalmente (D4Sign) em 12/09.\nEscopo: 12 unidades, 40 licenças, treinamento incluso.\n\n✅ Assinatura\n🔧 Kickoff agendado\n⬜ Pagamento da entrada (50%)\n\nMarco inicial: R$ 74,5k. Saldo em 3 parcelas.',
      color: 'verde',
      categoryId: 'cat_comercial',
      tags: ['venda', 'contrato', 'kickoff'],
      pinned: true,
      priority: 'alta',
      stage: 'venda',
      inPipeline: true,
      order: 1,
      company: 'Rede BemEstar Farmácias',
      client: 'Otávio Cardoso',
      email: 'otavio.cardoso@redebemestar.com.br',
      phone: '(11) 97711-9090',
      dealValue: 149000,
      dueDate: at(5 * DAY),
      checklist: [check('Assinatura do contrato', true), check('Kickoff agendado', true), check('Pagamento da entrada', false)],
      history: [hist('Contrato assinado — venda confirmada.', ago(6 * DAY))],
      createdAt: ago(48 * DAY),
      updatedAt: ago(6 * DAY),
    }),
    n({
      id: 'note_venda_aurora',
      title: 'Fintech Aurora — consultoria DevOps',
      content:
        'Proposta de 3 meses de consultoria (CI/CD, observabilidade, IaC).\nValor: R$ 96k. Pagamento mensal.\n\nJurídico da Aurora pediu ajuste na cláusula de propriedade intelectual.\nEnviar contrato revisado até quarta.',
      color: 'esmeralda',
      categoryId: 'cat_comercial',
      tags: ['venda', 'devops', 'contrato'],
      priority: 'urgente',
      stage: 'venda',
      inPipeline: true,
      order: 2,
      company: 'Fintech Aurora Pagamentos',
      client: 'Rafaella Pires (CTO)',
      email: 'rafaella.pires@aurora.pay',
      phone: '(11) 95021-4477',
      dealValue: 96000,
      dueDate: at(2 * DAY),
      createdAt: ago(26 * DAY),
      updatedAt: ago(2 * DAY),
    }),

    // ───────────── PIPELINE · FECHAMENTO ─────────────
    n({
      id: 'note_fech_vertex',
      title: 'Grupo Vertex — suporte gerenciado 12 meses (GANHO)',
      content:
        '✅ Fechado em 02/09 — R$ 78k/ano.\nImplantação do monitoramento concluída. 24 chamados atendidos no primeiro mês, SLA médio de 22 min.\n\nRenovação: acompanhar NPS em janeiro.\nUpsell identificado: backup gerenciado (+R$ 1,4k/mês).',
      color: 'turquesa',
      categoryId: 'cat_suporte',
      tags: ['fechamento', 'ganho', 'upsell'],
      pinned: true,
      priority: 'media',
      stage: 'fechamento',
      inPipeline: true,
      order: 1,
      company: 'Grupo Vertex S.A.',
      client: 'Luís Otávio Prado',
      email: 'luis.prado@vertexsa.com.br',
      phone: '(11) 93322-1188',
      dealValue: 78000,
      history: [hist('Contrato fechado e implantado.', ago(16 * DAY)), hist('Primeiro relatório mensal entregue.', ago(3 * DAY))],
      createdAt: ago(60 * DAY),
      updatedAt: ago(3 * DAY),
    }),
    n({
      id: 'note_fech_vilanova',
      title: 'Prefeitura de Vila Nova — implantação completa (GANHO)',
      content:
        '✅ Fechado — R$ 210k (licitação vencida).\nMarco 1 entregue, glosa de 5% liberada.\n\nPróximo pagamento vinculado à entrega do módulo de transparência (marco 2).\nRelacionamento: secretário pediu proposta de extensão para a educação.',
      color: 'verde',
      categoryId: 'cat_comercial',
      tags: ['fechamento', 'ganho', 'licitacao'],
      priority: 'alta',
      stage: 'fechamento',
      inPipeline: true,
      order: 2,
      company: 'Prefeitura de Vila Nova',
      client: 'Secretário Gilmar Souza',
      email: 'gilmar.souza@vilanova.sp.gov.br',
      phone: '(14) 98111-2255',
      dealValue: 210000,
      dueDate: at(20 * DAY),
      history: [hist('Licitação vencida e contrato assinado.', ago(40 * DAY))],
      createdAt: ago(90 * DAY),
      updatedAt: ago(9 * DAY),
    }),

    // ───────────── NOTAS GERAIS (fora do pipeline) ─────────────
    n({
      id: 'note_reuniao_semanal',
      title: 'Reunião semanal do time de engenharia',
      content: 'Toda segunda às 9h30 — sala 2 / Meet. Pauta fixa: sprint, bloqueios e deploy.',
      color: 'ciano',
      categoryId: 'cat_reunioes',
      tags: ['reuniao', 'time', 'semanal'],
      pinned: true,
      priority: 'media',
      checklist: [
        check('Revisar burndown do sprint', true),
        check('Definir responsáveis dos bloqueios', true),
        check('Planejar janela de deploy (quinta 20h)', false),
        check('Atualizar documentação do onboarding', false),
      ],
      createdAt: ago(12 * DAY),
      updatedAt: ago(1 * DAY),
    }),
    n({
      id: 'note_financeiro_setembro',
      title: 'Financeiro — contas do mês',
      content:
        'Vencimentos e conciliações de setembro.\n\n• NF 2024 — Prisma: R$ 27,4k (vencida, cobrar)\n• NF 2025 — BemEstar: R$ 74,5k (entrada)\n• AWS: R$ 6.180,00 — dia 20\n• Folha + benefícios: dia 5\n\nImpostos: Simples Nacional apurado, guia gerada.',
      color: 'esmeralda',
      categoryId: 'cat_financeiro',
      tags: ['financeiro', 'boletos', 'nf'],
      pinned: true,
      priority: 'urgente',
      checklist: [check('Emitir NF 2025 — BemEstar', true), check('Cobrar NF 2024 — Prisma', false), check('Pagar AWS', false), check('Conferir extrato e conciliar', false)],
      dueDate: localDateTime(2 * DAY, 18, 0),
      createdAt: ago(10 * DAY),
      updatedAt: ago(4 * HOUR),
    }),
    n({
      id: 'note_script_prospeccao',
      title: 'Script de prospecção (cold call)',
      content:
        '1) Contexto: "Vi que a {empresa} está expandindo para {cidade}..."\n2) Dor: perguntas de diagnóstico (o que mais consome tempo do time hoje?)\n3) Prova: case do Grupo Vertex (SLA 22 min)\n4) Convite: diagnóstico gratuito de 30 min\n\nObjeções:\n"Caro" → comparar com custo do retrabalho\n"Já tenho fornecedor" → propor piloto de 30 dias',
      color: 'azul',
      categoryId: 'cat_comercial',
      tags: ['comercial', 'script', 'cold-call'],
      priority: 'media',
      createdAt: ago(7 * DAY),
      updatedAt: ago(7 * DAY),
    }),
    n({
      id: 'note_suporte_sla',
      title: 'Suporte — horários de plantão e SLA',
      content:
        'Plantão comercial: seg a sex, 8h–18h.\nPlantão crítico: 24/7 (escala rotativa).\n\nSLA: crítico 15 min · alto 1h · médio 4h · baixo 1 dia útil.\nEscalonamento: N1 → N2 (tech lead) → N3 (arquiteto).',
      color: 'laranja',
      categoryId: 'cat_suporte',
      tags: ['suporte', 'sla', 'escalonamento'],
      priority: 'alta',
      createdAt: ago(22 * DAY),
      updatedAt: ago(11 * DAY),
    }),
    n({
      id: 'note_onboarding_cliente',
      title: 'Checklist de onboarding de cliente novo',
      content: 'Padrão para todo cliente que assina contrato (prazo: 5 dias úteis).',
      color: 'indigo',
      categoryId: 'cat_comercial',
      tags: ['onboarding', 'processo'],
      checklist: [
        check('Contrato assinado e arquivado', true),
        check('Criar pasta no Drive e canal no Slack', true),
        check('Criar acessos e ambiente do cliente', false),
        check('Reunião de kickoff com stakeholders', false),
        check('Plano de comunicação e prazos', false),
        check('Pesquisa de satisfação (30 dias)', false),
      ],
      createdAt: ago(19 * DAY),
      updatedAt: ago(2 * DAY),
    }),
    n({
      id: 'note_roadmap_q4',
      title: 'Roadmap Q4 — produto',
      content:
        'Foco: reter os 12 clientes ativos e reduzir chamados repetidos.\n\n• Módulo de relatórios self-service (maior pedido)\n• Autenticação SSO\n• Exportação XLSX/CSV\n• Melhorias de performance (consultas < 300 ms)\n• App mobile: aprovação de solicitações\n\nMeta: -30% de chamados de suporte até dezembro.',
      color: 'violeta',
      categoryId: 'cat_produto',
      tags: ['produto', 'roadmap', 'q4'],
      pinned: true,
      priority: 'alta',
      dueDate: localDateTime(9 * DAY, 17, 0),
      createdAt: ago(15 * DAY),
      updatedAt: ago(12 * HOUR),
    }),
    n({
      id: 'note_marketing_conteudo',
      title: 'Marketing — calendário de conteúdo',
      content:
        '3 posts/semana: case de cliente, dica técnica e bastidor.\n\n• Carrossel: "5 sinais de que você precisa de um CRM"\n• Artigo: integração NF-e sem dor\n• Webinar: automação de atendimento com IA (convidar FitLife)\n\nCanais: LinkedIn (principal) + Instagram + newsletter mensal.',
      color: 'rosa',
      categoryId: 'cat_marketing',
      tags: ['marketing', 'conteudo', 'linkedin'],
      priority: 'baixa',
      createdAt: ago(6 * DAY),
      updatedAt: ago(6 * DAY),
    }),
    n({
      id: 'note_infra_servidores',
      title: 'Infraestrutura — servidores e rotinas',
      content:
        'Ambientes: produção (2x app + 1 db), homologação, staging.\nBackup: diário 02h (retenção 30 dias) + snapshot semanal.\n\nRotinas de verificação: espaço em disco, certificados SSL, logs de erro.\nCredenciais ficam no cofre corporativo — nunca nesta nota.',
      color: 'grafite',
      categoryId: 'cat_infra',
      tags: ['infra', 'backup', 'devops'],
      priority: 'alta',
      createdAt: ago(40 * DAY),
      updatedAt: ago(8 * DAY),
    }),
    n({
      id: 'note_reembolso_viagem',
      title: 'Reembolso — viagem a São Paulo',
      content: 'Visita à Construtora Horizonte e Seguradora Prisma (2 dias).',
      color: 'amarelo',
      categoryId: 'cat_financeiro',
      tags: ['financeiro', 'reembolso', 'viagem'],
      priority: 'baixa',
      checklist: [check('Aéreo R$ 842,30', true), check('Hotel R$ 690,00', true), check('Uber R$ 178,90', true), check('Jantar com cliente R$ 312,00 — anexar nota', false)],
      createdAt: ago(5 * DAY),
      updatedAt: ago(5 * DAY),
    }),
    n({
      id: 'note_arquivada_campanha',
      title: 'Campanha de fim de ano — resultados',
      content:
        'Encerrada em 22/12. 214 leads gerados, 23 reuniões agendadas, 4 contratos (R$ 190k).\nCAC: R$ 1.180 por contrato. Melhor canal: LinkedIn Ads.\nAprendizado para a próxima edição: landing page precisa de prova social.',
      color: 'cinza',
      categoryId: 'cat_marketing',
      tags: ['marketing', 'resultado', 'encerrado'],
      archived: true,
      priority: 'baixa',
      createdAt: ago(120 * DAY),
      updatedAt: ago(95 * DAY),
    }),
    n({
      id: 'note_arquivada_evento',
      title: 'Tech Sul 2025 — anotações do evento',
      content:
        'Palestras sobre observabilidade e FinOps.\nContatos feitos: 31 (14 com fit).\nConcorrente que apareceu forte: Solaris Sistemas — posicionamento em preço baixo.',
      color: 'areia',
      categoryId: 'cat_reunioes',
      tags: ['evento', 'networking'],
      archived: true,
      priority: 'baixa',
      createdAt: ago(70 * DAY),
      updatedAt: ago(64 * DAY),
    }),
    n({
      id: 'note_lixeira_rascunho',
      title: 'Rascunho antigo de proposta (descartado)',
      content: 'Modelo de proposta em Word que foi substituído pelo gerador de propostas no Notion.',
      color: 'padrao',
      categoryId: 'cat_comercial',
      tags: ['rascunho'],
      trashed: true,
      trashedAt: ago(6 * DAY),
      priority: 'baixa',
      createdAt: ago(80 * DAY),
      updatedAt: ago(6 * DAY),
    }),
  ].map((note) => ({ ...note, categoryId: note.categoryId ?? null }))

  const reminders = [
    { id: 'rem_001', noteId: 'note_atend_horizonte', title: 'Ligar para Marcos Tavares (Horizonte) — confirmar diagnóstico', at: at(1 * MIN + 20 * 1000), repeat: 'none', done: false, active: true, createdAt: ago(2 * DAY) },
    { id: 'rem_002', noteId: 'note_financeiro_setembro', title: 'Cobrar NF 2024 da Seguradora Prisma', at: ago(35 * MIN), repeat: 'none', done: false, active: true, createdAt: ago(3 * DAY) },
    { id: 'rem_003', noteId: 'note_apres_prisma', title: 'Cobrar aprovação formal do comitê — Prisma', at: at(70 * MIN), repeat: 'none', done: false, active: true, createdAt: ago(1 * DAY) },
    { id: 'rem_004', noteId: 'note_apres_energia', title: 'Reunião de apresentação — Energia Renovável BR', at: localDateTime(1 * DAY, 10, 0), repeat: 'none', done: false, active: true, createdAt: ago(4 * DAY) },
    { id: 'rem_005', noteId: 'note_atend_fitlife', title: 'Follow-up WhatsApp — FitLife Academias', at: localDateTime(2 * DAY, 14, 30), repeat: 'none', done: false, active: true, createdAt: ago(2 * DAY) },
    { id: 'rem_006', noteId: 'note_venda_aurora', title: 'Enviar contrato revisado (cláusula de PI) — Aurora', at: localDateTime(1 * DAY, 16, 0), repeat: 'none', done: false, active: true, createdAt: ago(1 * DAY) },
    { id: 'rem_007', noteId: 'note_suporte_sla', title: 'Revisar escala de plantão da semana', at: localDateTime(0, 18, 0), repeat: 'weekly', done: false, active: true, createdAt: ago(20 * DAY) },
    { id: 'rem_008', noteId: 'note_infra_servidores', title: 'Verificar backup e espaço em disco', at: localDateTime(1 * DAY, 9, 0), repeat: 'daily', done: false, active: true, createdAt: ago(30 * DAY) },
    { id: 'rem_009', noteId: 'note_financeiro_setembro', title: 'Fechamento financeiro mensal', at: localDateTime(12 * DAY, 17, 0), repeat: 'monthly', done: false, active: true, createdAt: ago(25 * DAY) },
    { id: 'rem_010', noteId: 'note_roadmap_q4', title: 'Revisão do roadmap com o time de produto', at: localDateTime(6 * DAY, 11, 0), repeat: 'none', done: false, active: true, createdAt: ago(5 * DAY) },
    { id: 'rem_011', noteId: 'note_fech_vertex', title: 'Enviar relatório mensal ao Grupo Vertex', at: ago(2 * DAY), repeat: 'none', done: true, active: true, createdAt: ago(10 * DAY) },
  ]

  const settings = {
    theme: 'light',
    soundEnabled: true,
    sound: 'chime',
    volume: 0.7,
    notificationsEnabled: false,
    mondayFirst: true,
  }

  return { notes, categories, reminders, settings, seededAt: new Date().toISOString(), version: 1 }
}
